### ISSUE TITLE
bug: todo-comments not working properly

### ISSUE THREAD

**Issue by Mat-moran** [LazyVim/LazyVim#1400]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

MacOs Ventura 13.4.1

### Describe the bug

Todo comments are not working.
- No colors
- No find TODO when `<leader>xt`

### Steps To Reproduce

1. Install lunar vim
2. Open a typescript project 
3. put a `// TODO` comment
4. You won't see it colorized and you can not fin it wit `<leader>xt`

### Expected Behavior

With the default config, 
- should be colorized
- you should be able to find TODO comments with `<leader>xt`

### Repro

```Lua
default config
```

**Comment by abeldekat** [comment]
Hello @Mat-moran,

In your steps to reproduce, I assume you intended to write "LazyVim" instead of "LunarVim".

The TODO comment needs to be followed by a colon in order to be recognized by the plugin.

From the [docs](https://github.com/folke/todo-comments.nvim#-usage):
> Todo matches on any text that starts with one of your defined keywords (or alt) followed by a colon:

**Comment by Mat-moran** [comment]
> Hello @Mat-moran,
> 
> In your steps to reproduce, I assume you intended to write "LazyVim" instead of "LunarVim".

Yes sorry, changed.

> The TODO comment needs to be followed by a colon in order to be recognized by the plugin.
> 
> From the [docs](https://github.com/folke/todo-comments.nvim#-usage):
> 
> > Todo matches on any text that starts with one of your defined keywords (or alt) followed by a colon:
 OK thanks you very much ! my fault 😅
